name: SafeTrade
version: 1.0.16
author: BtoBastian
main: de.oppermann.bastian.safetrade.Main
softdepend: [Vault]
commands:
   trade:
     description: Starts a trade. More information with /trade help!
     aliases: [safetrade]