name: SafeTrade
version: 1.1.0
author: BtoBastian
main: de.oppermann.bastian.safetrade.Main
api-version: 1.13
softdepend: [Vault]
commands:
   trade:
     description: Starts a trade. More information with /trade help!
     aliases: [safetrade]